name: "Pull Requests Labeler"
on:
- pull_request

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/pull_requests_labeler.yml"
